[Feature] Kakao login manager
DDD-Community/MorningBear-iOS pull request #23
Opened 2022-12-08 04:58 UTC by 2dubu

2022-12-08 05:53 UTC, enebin requested changes

2022-12-08 05:53 UTC, enebin commented on Targets/MorningBear/Sources/AuthViewController.swift
> +        // kakaoLoginManager.login()
메소드 이름 통일 부탁. 애플이랑 카카오랑

2022-12-08 05:53 UTC, enebin commented on Targets/MorningBearKit/Sources/Auth/KakaoLoginManager.swift
> +    private let disposeBag = DisposeBag()
이름 `bag`으로 변경

2022-12-08 05:53 UTC, enebin commented on Targets/MorningBearKit/Sources/Auth/KakaoLoginManager.swift
> +    public func login() {
(옵셔널... 인데 웬만하면 했으면 좋겠는) 
- 뷰 컨트롤러로 에러 던질 수 있게 throws 처리 하거나 errorHandler. 아님 Rx Single이나 Observable로 던져도 됨.
- 애플로그인도 마찬가지

아래 메소드들도 다 마찬가진데 하기 힘들면 놔두셈. 어차피 뷰 나오면 대부분 뷰모델로 빠질 것 같음.

2022-12-08 05:53 UTC, enebin commented on Targets/MorningBearKit/Sources/Auth/KakaoLoginManager.swift
> +    public func setUserInfo() {
얜 어디에 쓰는거야? 매개변수도 없고 리턴도 없길래

2022-12-08 05:53 UTC, enebin commented on Tuist/Dependencies.swift
> +            requirement: .branch("master")
마스터 말고 위 파이어베이스처럼 버전 명시

2022-12-08 05:54 UTC, enebin commented
➕ 메소드 어떤 방식이든 테스트 해보고 동작 제대로 하는지도 체크 부탁

2022-12-08 09:59 UTC, 2dubu commented on Tuist/Dependencies.swift
> +            requirement: .branch("master")
@enebin 카카오 문서에 master를 쓰라고 명시되어 있었는데 그래도 바꾸는게 좋을까요?

2022-12-09 04:09 UTC, enebin approved these changes

2022-12-09 10:57 UTC, merged